// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXToa2hSL8cqa6f41Rcj6ohyQZCmZp9mY',
    appId: '1:79667505598:web:6db3cac7d43f237a1731ef',
    messagingSenderId: '79667505598',
    projectId: 'food-9d1af',
    authDomain: 'food-9d1af.firebaseapp.com',
    storageBucket: 'food-9d1af.firebasestorage.app',
    measurementId: 'G-347V09ZY3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXOwZ5vEuwgDSKCPo6FvpY9hKQsbKnBDw',
    appId: '1:79667505598:android:96ee03b52635992a1731ef',
    messagingSenderId: '79667505598',
    projectId: 'food-9d1af',
    storageBucket: 'food-9d1af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP-ipQtLSdY6geuXgDo1PRk3ZbcENyQVI',
    appId: '1:79667505598:ios:8237436b67ce51181731ef',
    messagingSenderId: '79667505598',
    projectId: 'food-9d1af',
    storageBucket: 'food-9d1af.firebasestorage.app',
    iosClientId: '79667505598-lpanlk6dnettuhe9l22j2onok7apv17q.apps.googleusercontent.com',
    iosBundleId: 'com.codingwitht.foodu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP-ipQtLSdY6geuXgDo1PRk3ZbcENyQVI',
    appId: '1:79667505598:ios:be2591479e633a951731ef',
    messagingSenderId: '79667505598',
    projectId: 'food-9d1af',
    storageBucket: 'food-9d1af.firebasestorage.app',
    iosClientId: '79667505598-n5garctsvgq3qpu2npv63dklgjkcv80n.apps.googleusercontent.com',
    iosBundleId: 'com.delivery.foodu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXToa2hSL8cqa6f41Rcj6ohyQZCmZp9mY',
    appId: '1:79667505598:web:74bf6da5beb549801731ef',
    messagingSenderId: '79667505598',
    projectId: 'food-9d1af',
    authDomain: 'food-9d1af.firebaseapp.com',
    storageBucket: 'food-9d1af.firebasestorage.app',
    measurementId: 'G-RPC1CD3X6R',
  );

}